/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.github.goooler.shadow") version "8.1.7"
}

dependencies {
    api(project(":common"))
    compileOnly(libs.org.spongepowered.spongeapi)
    testImplementation(libs.org.spongepowered.spongeapi)
}

tasks {
    build {
        dependsOn(shadowJar)
    }

    test {
        useJUnitPlatform()
    }
}

java.targetCompatibility = JavaVersion.VERSION_21

group = "dev.thomazz.pledge"
description = "sponge"
