/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.spongepowered.org/repository/maven-public/")
    }
}

dependencies {
    api("org.jetbrains:annotations:24.0.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("org.mockito:mockito-core:3.12.4")
    testImplementation("org.mockito:mockito-junit-jupiter:3.12.4")
    testImplementation("io.netty:netty-all:4.1.42.Final")
    compileOnly("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
    compileOnly("io.netty:netty-all:4.1.42.Final")
    compileOnly("org.slf4j:slf4j-api:2.0.12")
    compileOnly("com.google.guava:guava:33.0.0-jre")
}

group = "dev.thomazz"
version = "3.0"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.empirewar.pledge"
            artifactId = project.name
            version = project.version.toString()
            from(components["java"])
        }
    }

    repositories {
        // See Gradle docs for how to provide credentials to PasswordCredentials
        // https://docs.gradle.org/current/samples/sample_publishing_credentials.html
        maven {
            val snapshotUrl = "https://repo.convallyria.com/snapshots/"
            val releaseUrl = "https://repo.convallyria.com/releases/"

            // Check which URL should be used
            url = if (project.version.toString().endsWith("SNAPSHOT")) {
                uri(snapshotUrl)
            } else {
                uri(releaseUrl)
            }

            name = "snapshots"
            url = uri("https://repo.convallyria.com/snapshots/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}
